# Generated by Django 3.2.9 on 2022-10-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crawlingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('company', models.TextField()),
                ('tech', models.TextField()),
            ],
        ),
    ]
